{% set name = "llama-index-embeddings-openai" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_embeddings_openai-{{ version }}.tar.gz
    sha256: 0047dd71d747068645ed728c29312aa91b65bbe4c6142180034c64dfc5c6f6e8
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - openai >=1.1.0
    - python >=3.8.1,<4.0
    - llama-index-core >=0.11.0,<0.12.0

test:
  imports:
    - llama_index.embeddings.openai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/embeddings/llama-index-embeddings-openai
  summary: llama-index embeddings openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
